### ISSUE TITLE
IllegalStateException on scala2.13.1 and 3.1.3

### ISSUE THREAD

**Issue by rxda** [findify/flink-scala-api#15]
Hi,I'm trying to use flink in scala3,but there are some problems.

This is build.sbt
```
name := "flink-scala-3"

version := "0.1"

scalaVersion := "3.1.3"

resolvers += Resolver.mavenLocal

javacOptions ++= Seq("-source", "11", "-target", "11")

libraryDependencies += "org.apache.flink" % "flink-streaming-java" % "1.15.1" % "provided"
libraryDependencies += "org.apache.flink" % "flink-clients" % "1.15.1"
libraryDependencies += "io.findify" %% "flink-scala-api" % "1.15-2"
libraryDependencies += "io.findify" %% "flink-adt" % "0.6.1"
```
And this is flink code(word count example)
```
import io.findify.flink.api._
import io.findify.flinkadt.api._

@main def example0 =
  val env = StreamExecutionEnvironment.getExecutionEnvironment
  env.readTextFile("input/words.txt")
    .flatMap(_.split(" "))
    .map(value => (value, 1))
    .keyBy(_._1)
    .sum(1)
    .print()

  env.execute()
```
It reported error when I ran the code locally:

```
Exception in thread "main" java.lang.IllegalStateException: Scala products are used but Scala API is not on the classpath.
	at org.apache.flink.streaming.util.typeutils.FieldAccessorFactory.getAccessor(FieldAccessorFactory.java:99)
	at org.apache.flink.streaming.api.functions.aggregation.SumAggregator.<init>(SumAggregator.java:41)
	at io.findify.flink.api.KeyedStream.aggregate(KeyedStream.scala:423)
	at io.findify.flink.api.KeyedStream.sum(KeyedStream.scala:353)
	at com.ververica.Example_00$package$.example0(Example_00.scala:13)
	at com.ververica.example0.main(Example_00.scala:7)
```

this is code repository
[repositorie](https://github.com/rxda/flink-scala3-demo)

Is there any way to solve this problem? Thank you! 
(I'm not English native speaker, please forgive me if I have offended you in any way)

**Comment by rxda** [comment]
If chagne flink code to this, it works
```
import io.findify.flink.api._
import io.findify.flinkadt.api._

@main def example0 =
  val env = StreamExecutionEnvironment.getExecutionEnvironment
  env.readTextFile("input/words.txt")
    .flatMap(_.split(" "))
    .map(value => (value, 1))
    .print()

  env.execute()
```

**Comment by novakov-alexey** [comment]
Try to add one more dependency which contains some required Scala factory class:

```
"org.apache.flink" % "flink-streaming-scala_2.12" % "1.15.2"
```

**Comment by rxda** [comment]
> Try to add one more dependency which contains some required Scala factory class:
> 
> ```
> "org.apache.flink" % "flink-streaming-scala_2.12" % "1.15.2"
> ```

thank you, it works correctly
